version: '3.9'
services:
  db-husky:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - husky-challenge
  
  redis:
    image: 'redis:6.2.6-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - husky-challenge

  sidekiq:
    build: .
    # command: bundle exec sidekiq -C ./config/sidekiq.yml
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db-husky
      - redis
    networks:
      - husky-challenge
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db-husky
      - redis
      - sidekiq
    networks:
      - husky-challenge
    env_file:
      - .env
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0

networks:
  husky-challenge:
    driver: bridge

volumes:
  postgres-data:
  # redis:
